version: "3"

services:
  db:
    image: postgres
    container_name: container_php_stripe_postgresql
    environment:
      POSTGRES_PASSWORD: testing
      POSTGRES_USER: test
      POSTGRES_DB: db_test_stripe
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432
    volumes:
      - /home/jmariona/Desktop/DocumentsRoot/PRACTICES/PHP/htdocs/phpPDO/data:/var/lib/postgresql/data/pgdata
